// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/9/9 23:39:18
const configMerger = require("/Users/masaki/Develop/PhotoGallery/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
(() => {const cfg=configMerger(undefined, require("./../tailwind.config.js"));cfg.content = cfg.purge;;return cfg;})()
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/masaki/Develop/PhotoGallery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/plugins/**/*.{js,ts,mjs}","/Users/masaki/Develop/PhotoGallery/composables/**/*.{js,ts,mjs}","/Users/masaki/Develop/PhotoGallery/utils/**/*.{js,ts,mjs}","/Users/masaki/Develop/PhotoGallery/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/masaki/Develop/PhotoGallery/app.config.{js,ts,mjs}"] }));

module.exports = config
